"""
Fabric tasks that go beyond the Sphinx Makefile.

We don't want to mess with the Makefile because it was autogenerated by
Sphinx.

"""
from fabric.api import local


def html():
    """Generates the api-doc and the html output."""
    local('rm -rf source/api')
    local('sphinx-apidoc -f -o source/api ../pyconsg')
    local('make html')
